### ISSUE TITLE
Translation advice

### ISSUE THREAD

**Issue by yinx2002** [Pruszko/DispersionReticle#12]
I have noticed in translations_zh_cn.json,  English text of Chinese translation have been added in previous commit as well as in other translation (pl ru).  

But I strongly recommend not doing that at least in Chinese language. (only leave pure Chinese is OK). Unlike other alphabetical language ， Chinese language only consists of "symbols" but not letters. As the experience of mine, English letters among a bunch of Chinese will make them feel strange, some one will treat English text as "error code" or "messy text" cause most developer will only use English text in core level error message.

**Comment by yinx2002** [comment]
Of course, some innevitable ones like in combobox are exceptions.

**Comment by Pruszko** [comment]
Yes, in translations other than English I've purposely added English translations in parentheses for those terms that are hardwritten in images (similarly those in combobox) because translations are not always 1:1 accurate (for example those for `Latency reticle`).  
And adding images for each language is an overkill.

From my experience, in language model based on alphabet, foreign terms don't interfere in sentences (even cyrilic words in English sentence aren't that bad).  
However, I can imagine that sentences in language based on symbols can be weird when having words from completely different model.

In alphabet-based languages I'd like to maintain translations as it is, but for `zh_cn` parentheses can be removed + add ability to translate combobox values (if that is possible)

**Comment by Pruszko** [comment]
Pushed branch `2.6.1`.

You can make final adjustment with pull request if you want or answer here if nothing more is needed

**Comment by yinx2002** [comment]
Thanks for efforts ， let me take a look

**Comment by yinx2002** [comment]
I just have an idea. Cause the initial purpose that you add English text after translated text in parenthensis is to identify which part a config section refers to in the image (and this a real problem). Maybe we can use digit ,like ①②③ in the image and also add text  in translation. I think that will solve the initial problem.

**Comment by Pruszko** [comment]
I have through about numbering them.  
For shape selection it would work quite well if it was like that for example:
* combobox: `1. <translated shape>`
* on image: just written `1.`

However, for reticle types, it would be "much more messy" because there would have to be numbering with arrows pointing to certain reticle on the image and prefixing/suffixing reticle type with `1.` would look akward. For example:
* `1. <translated reticle>` (and on image just written `1.` with pointing arrow)
* some config options related to that reticle
* `2. <other translated reticle>` <-- this looks akward because between `1.` and `2.` there are other parameters
* suffixed numbering would look like count or something

Still have to think about that

**Comment by Pruszko** [comment]
I'll probably sit to it around weekend

Maybe something like this?
* numerate reticles/shapes on image previews
  * I have saved original images if I remember correctly
* add in translation of reticle/shape something with `image` word and a number in parentheses
  * something like `Dispersion reticle (no. 1 on image)`
  * similarly with shapes, like `Pentagon (image 1)`

I'd rather avoid putting number alone in parenthesis

**Comment by Pruszko** [comment]
I pushed to branch `2.6.1` new images and changes to translations.  
Now images have numeration - just prefixed reticles and shapes with number (ex. reticle `1. Dispersion reticle`, shape `3. Circle`)

Added possibility to translate shapes - you can make pull request to branch `2.6.1` with final translation adjustments.
I added default ones to `translations_zh_cn.json`

**Comment by yinx2002** [comment]
committed

**Comment by Pruszko** [comment]
Released in version `2.6.1`.

If you have more ideas/suggestions, feel free to PM me or make another request :)

**Comment by yinx2002** [comment]
I have installed new 2.6.1 version, and the translation looks great and neat, only a small question:

In the combobox, the entries are translated, but there are digit before them as well as the reticles image, and also 1,2,3,4 
maybe  remove the digits will be better.

**Comment by Pruszko** [comment]
I've prefixed shapes in combobox with digits to match them with their tooltip image ([simple_reticle.jpg](https://github.com/Pruszko/DispersionReticle/blob/master/src/gui/dispersionreticle/imgs/simple_server.jpg)), similarly as for reticles

Should it be changed? Otherwise there wouldn't be any clear indication which shape translation belongs to target shape

**Comment by yinx2002** [comment]
I forget this simple_reticle image,  just thought it was something like series number.   Actually, I just mean maybe we should change to some other tag so that they will not be the same in reticle image  ([all.jpg]https://github.com/Pruszko/DispersionReticle/blob/master/src/gui/dispersionreticle/imgs/all.jpg)

**Comment by Pruszko** [comment]
I think it will be the best to remove those prefixes in `shape` parameter because shapes in combobox can be designated from image by position in the combobox.

I'm currently working on version 3.0.0 which changes a lot of stuff, including variations of simple reticles to `dispersion` and `latency` reticles, so I can include this change in that version.

Because of quite a lot of features and changes, I'd like to ask You for support with Chinese translations when I push `3.0.0` branch to repo.  
If you don't mind, I'll reanswer here to notify You when everything will be ready for translation

Happy new year!

**Comment by yinx2002** [comment]
Great to hear this project has active developing plan. Chinese translation support will surely be provided.

**Comment by Pruszko** [comment]
Hi, I've published `3.0.0` beta version with it's branch in #7 issue.

Read notes in the comment before using this version and translating.  
It has only partially present translations, so you might need to recheck them again

**Comment by Pruszko** [comment]
Currently released all changes in version `3.0.0`

I've removed number prefix in comboboxes because by ordinal you can guess which option is which on image.

I also removed number prefixes in reticles, but I left them in tooltip header, so users looking at image can still guess them.  
This should be a good compromise

You can add me on discord `fierioziy` to have more reliable contact in future :)
