### ISSUE TITLE
Dual Accuracy Tanks - 3.0.2 vs 3.0.3

### ISSUE THREAD

**Issue by Zavars** [Pruszko/DispersionReticle#18]
With 3.0.3 and my same configuration only using the Server Reticle Extended option, for the dual accuracy tanks, the non-cooled dispersion circle is always showing. I didn't see this with 3.0.2. Is there an option that I have mistakenly selected or is this the intended behaviour? I've attached a screenshot of how 3.02 vs 3.0.3 looked with my config, along with a copy of my config file.

![DR_3 0 2](https://github.com/Pruszko/DispersionReticle/assets/43646276/22c7685b-cfa7-4a4f-adf0-0130e6d61406)
![DR_3 0 3](https://github.com/Pruszko/DispersionReticle/assets/43646276/74c2fba4-99e5-4184-bfe7-675bd072e3cc)
[config.json](https://github.com/Pruszko/DispersionReticle/files/14016370/config.json)

**Comment by Pruszko** [comment]
Yes, this is intended behavior

Mentioned in 3.0.3 changelog:
> dual accuracy can now be displayed when using both client-side and server-side reticles simultaneously

I'm displaying it like on your screens, because in non-modded WoT, this non-cooled dispersion circle is showing in such conditions:
* when dual accuracy tank fully focused reticle past cooldown timer
* `Use server aim` in game settings is **unchecked**

When `Use server aim` is **checked**, then game does not display non-cooled dispersion circle, because this particular reticle is **client-side only**. And that also happened when using `server-reticle` (or `extended`), because game exlicitly disables dual accuracy reticle when it detects server aiming enabled.

I've made an exception to this rule by allowing to display it, because:
* non-cooled dispersion circle is **client-side reticle**
* client-side reticle is visible while using `server-reticle` (or `extended`)

**Comment by Zavars** [comment]
Thanks for the clarification! I wasn't sure if it was optional or default. Though I do like how it looks in the latest version!

**Comment by Pruszko** [comment]
You're welcome

If you have more questions, don't hesitate to open this or make new ticket for that :)
