### ISSUE TITLE
DispersionReticle v3.0.5

### ISSUE THREAD

**Issue by Zavars** [Pruszko/DispersionReticle#19]
Hi Pruszko,

I updated to the latest version (3.0.5) from Aslains modpak and Server Reticle Extended is not showing up in battle. Unfortunately I haven't tried the others as of yet. Went back to 3.0.3 with the same config file and everything is working normally. This is on the NA client.

Python.log has multiple warnings. I've attached the python log from one battle with v3.0.5, which for some reason seems to be very large (for a single battle) and it's been truncated (size limit maybe?).

[python.log](https://github.com/Pruszko/DispersionReticle/files/14070927/python.log)
[config.json](https://github.com/Pruszko/DispersionReticle/files/14070929/config.json)

**Comment by Pruszko** [comment]
Hi Zavars,

Thanks for reporting. It looks like `NA` also has separate distinction in WG related clients same as `EU`, `ASIA` and `NA` (and probably others).

This version should 100% now work properly; issues started due to code changes `RU` specific which I handled improperly for clients others than `EU` and `RU`.  
[DispersionReticle_3.0.6.zip](https://github.com/Pruszko/DispersionReticle/files/14072425/DispersionReticle_3.0.6.zip)

If everything is ok, I'll release this hot fix and close this issue.  
Thanks again for checking things out :)

**Comment by Pruszko** [comment]
I've released version 3.0.6 with fixes due to importance of changes (they should be safe now).

If everything is ok now, feel free to close this ticket or comment with further issues :)

**Comment by Zavars** [comment]
Updated and played 1 game, seems to be working fine!
